# Generated by Django 4.2.6 on 2023-10-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='persons_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(default='555-555-5555', max_length=15),
        ),
        migrations.AddField(
            model_name='contact',
            name='your_email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='contact',
            name='your_message',
            field=models.TextField(default='Default message', max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='your_name',
            field=models.CharField(default='Default Name', max_length=30),
        ),
    ]
