# Generated by Django 4.2.6 on 2023-10-31 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='your_name',
            field=models.CharField(max_length=20),
        ),
    ]
