# Generated by Django 4.2.6 on 2023-11-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_contact_your_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
