# Generated by Django 4.2.6 on 2023-11-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_cartitems_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
