# Generated by Django 4.2.6 on 2023-10-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_contact_persons_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='your_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
