# Generated by Django 4.2.6 on 2023-11-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_checkout_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('upi', 'UPI ID')], max_length=50, null=True),
        ),
    ]
