# Generated by Django 4.2.6 on 2023-11-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_alter_paymentmethod_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('upi', 'UPI ID')], default='credit_card', max_length=50),
        ),
    ]
