# Generated by Django 4.2.6 on 2023-11-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_alter_paymentmethod_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
