# Generated by Django 4.2.6 on 2023-11-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_alter_checkout_address_alter_checkout_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
