# Generated by Django 4.2.6 on 2023-11-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_alter_checkout_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='email',
            field=models.EmailField(blank=True, max_length=300, null=True),
        ),
    ]
