# Generated by Django 4.2.6 on 2023-11-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0025_alter_checkout_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='address',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='email',
            field=models.EmailField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkout',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='state',
            field=models.CharField(max_length=100),
        ),
    ]
