# Generated by Django 4.2.6 on 2023-11-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0029_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card')], default='credit_card', max_length=50),
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
    ]
