# Generated by Django 4.2.6 on 2023-11-29 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0031_remove_checkout_payment_method_paymentmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='checkout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_method', to='order.checkout'),
        ),
    ]
